/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.uno;

import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Joseph F
 */
public class EscogerColor extends javax.swing.JFrame {

    private CartaUno.Color wildColor = null;
    Boolean permitido = false;
    PopUp popUp;
    
    
    /**
     * Creates new form PickColorFrame
     */
    public EscogerColor(){}
    
    public EscogerColor(PopUp pop) {
        initComponents();
        popUp = pop;
    }
    
    public CartaUno.Color choseColor(CartaUno carta){
        if(carta.obtenerColor()== CartaUno.Color.Wild){
            this.setVisible(true);
            this.setResizable(false);
            this.setBounds(100, 150, 600, 700);
        }
        return carta.obtenerColor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        redButton = new javax.swing.JButton();
        blueButton = new javax.swing.JButton();
        greenButton = new javax.swing.JButton();
        yellowButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Seleccione el color");

        redButton.setText("Rojo");
        redButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redButtonActionPerformed(evt);
            }
        });

        blueButton.setText("Azul");
        blueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueButtonActionPerformed(evt);
            }
        });

        greenButton.setText("Verde");
        greenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenButtonActionPerformed(evt);
            }
        });

        yellowButton.setText("Amarillo");
        yellowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yellowButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(redButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blueButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(greenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yellowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(redButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(blueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(greenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(yellowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void redButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redButtonActionPerformed
        wildColor =  CartaUno.Color.Rojo;
        JLabel message = new JLabel("Ahora el juego se debe jugar sobre las rojas!");
        message.setFont(new Font("Arial", Font.BOLD, 18));
        JOptionPane.showMessageDialog(null, message);
        permitido = true;
        this.dispose();
        popUp.ColorDeclarado = CartaUno.Color.Rojo;
        popUp.gameStage.PonerCodigoJugadores(popUp.juego.obtenerJugadorActual());
        popUp.gameStage.ponerIconoBotones();
        popUp.topCardButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Joseph F\\Desktop\\IMAGES\\Small\\" + popUp.juego.getImagenCartaArriba()));
        popUp.juego.establecerColorCarta(CartaUno.Color.Rojo);
        popUp.dispose();
    }//GEN-LAST:event_redButtonActionPerformed

    private void blueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueButtonActionPerformed
        wildColor =  CartaUno.Color.Azul;
        JLabel message = new JLabel("Ahora el juego se debe jugar sobre las Azules!");
        message.setFont(new Font("Arial", Font.BOLD, 18));
        JOptionPane.showMessageDialog(null, message);
        permitido = true;
        this.dispose();
        popUp.ColorDeclarado = CartaUno.Color.Azul;
        popUp.gameStage.PonerCodigoJugadores(popUp.juego.obtenerJugadorActual());
        popUp.gameStage.ponerIconoBotones();
        popUp.topCardButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Joseph F\\Desktop\\IMAGES\\Small\\" + popUp.juego.getImagenCartaArriba()));
        popUp.juego.establecerColorCarta(CartaUno.Color.Azul);
        popUp.dispose();
    }//GEN-LAST:event_blueButtonActionPerformed

    private void greenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenButtonActionPerformed
        wildColor =  CartaUno.Color.Verde;
        JLabel message = new JLabel("Ahora el juego se debe jugar sobre las Verdes!");
        message.setFont(new Font("Arial", Font.BOLD, 18));
        JOptionPane.showMessageDialog(null, message);
        permitido = true;
        this.dispose();
        popUp.ColorDeclarado = CartaUno.Color.Verde;
        popUp.gameStage.PonerCodigoJugadores(popUp.juego.obtenerJugadorActual());
        popUp.gameStage.ponerIconoBotones();
        popUp.topCardButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Joseph F\\Desktop\\IMAGES\\Small\\" + popUp.juego.getImagenCartaArriba()));
        popUp.juego.establecerColorCarta(CartaUno.Color.Verde);
        popUp.dispose();
    }//GEN-LAST:event_greenButtonActionPerformed

    private void yellowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yellowButtonActionPerformed
        wildColor =  CartaUno.Color.Amarillo;
        JLabel message = new JLabel("Ahora el juego se debe jugar sobre las Amarillas!");
        message.setFont(new Font("Arial", Font.BOLD, 18));
        JOptionPane.showMessageDialog(null, message);
        permitido = true;
        this.dispose();
        popUp.ColorDeclarado = CartaUno.Color.Amarillo;
        popUp.gameStage.PonerCodigoJugadores(popUp.juego.obtenerJugadorActual());
        popUp.gameStage.ponerIconoBotones();
        popUp.topCardButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Joseph F\\Desktop\\IMAGES\\Small\\" + popUp.juego.getImagenCartaArriba()));
        popUp.juego.establecerColorCarta(CartaUno.Color.Amarillo);
        popUp.dispose();
    }//GEN-LAST:event_yellowButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscogerColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscogerColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscogerColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscogerColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscogerColor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blueButton;
    private javax.swing.JButton greenButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton redButton;
    private javax.swing.JButton yellowButton;
    // End of variables declaration//GEN-END:variables
}
