/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.uno;

import java.awt.Font;
import java.util.logging.Logger;
import java.util.logging.Level;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.stream.Collectors;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Joseph F
 */
public class GameStage extends javax.swing.JFrame {

    private AgregarNombresJugadores AñadirJugadores = new AgregarNombresJugadores();
    ArrayList<String> temp = new ArrayList<>();
    String[] codigo_jugadores;
    Juego juego;
    ArrayList<JButton> BotonesCarta = new ArrayList<JButton>();
    ArrayList<String> IdCartas;
    PopUp ventana;

    /**
     * Creates new form GameStage
     */
    public GameStage() {
    }

    ;
    public GameStage(ArrayList<String> Codigo_Jugadores) throws BarajaUno.BarajaVaciaException {
        initComponents();
        temp = Codigo_Jugadores;
        codigo_jugadores = temp.toArray(new String[temp.size()]);
        juego = new Juego(codigo_jugadores);
        ArrayListDeGente();
        juego.iniciar(juego);
        PonerCodigoJugadores();
        //BotonCartaTop();
        BotonCartaTop.setIcon(new javax.swing.ImageIcon("C:\\Users\\Joseph F\\Desktop\\IMAGES\\Small\\" + juego.obtenerImagenCartaSuperior()));
        ponerIconoBotones();
    }
    
    int numBotones = BotonesCarta.size();
    int numIdCartas = IdCartas.size();

    public void ponerIconoBotones() {

        // Asegúrate de que ambos ArrayList tengan el mismo tamaño
        

    // Verifica que el tamaño de ambos ArrayList sea el mismo y que BotonesCarta no sea null
        if (BotonesCarta != null && numBotones == numIdCartas) {
            for (int i = 0; i < numBotones; i++) {
                // Construye la ruta del archivo de imagen
                String rutaImagen = "C:\\Users\\Joseph F\\Desktop\\IMAGES\\Small\\" + IdCartas.get(i) + ".png";

                // Verifica que el índice sea válido y que el botón no sea null antes de intentar establecer el ícono
                if (i < BotonesCarta.size() && BotonesCarta.get(i) != null) {
                    // Establece el ícono del botón
                    BotonesCarta.get(i).setIcon(new javax.swing.ImageIcon(rutaImagen));
                } else {
                    // Manejar el caso en que el índice o el botón está fuera de rango
                    System.err.println("Índice o botón fuera de rango en el bucle: " + i);
                }
            }
        } else {
            // Manejar el caso en que BotonesCarta es null o los tamaños de los ArrayList no coinciden
            System.err.println("BotonesCarta es null o los tamaños de los ArrayList no coinciden.");
        }

        String listString = juego.obtenerManoJugador(juego.obtenerJugadorActual()).stream().map(Object::toString).collect(Collectors.joining(","));
        String[] NombreCartas = listString.split(",");
        IdCartas = new ArrayList<>(Arrays.asList(NombreCartas));

        for (int i = 0; i < IdCartas.size(); i++) {
            BotonesCarta.get(i).setIcon(new javax.swing.ImageIcon("C:\\Users\\Joseph F\\Desktop\\IMAGES\\Small\\" + IdCartas.get(i) + ".png"));
        }

        for (int i = IdCartas.size(); i < BotonesCarta.size(); i++) {
            BotonesCarta.get(i).setIcon(null);
        }
    }

    public void ArrayListDeGente() {
        BotonesCarta.add(jButton1);
        BotonesCarta.add(jButton2);
        BotonesCarta.add(jButton3);
        BotonesCarta.add(jButton4);
        BotonesCarta.add(jButton5);
        BotonesCarta.add(jButton6);
        BotonesCarta.add(jButton7);
        BotonesCarta.add(jButton8);
        BotonesCarta.add(jButton9);
        BotonesCarta.add(jButton10);
        BotonesCarta.add(jButton11);
    }

    public void PonerCodigoJugadores() {
        String JugadorActual = juego.obtenerJugadorActual();
        PonerNombreJugador.setText("Cartas de " + JugadorActual);
    }

    public void PonerCodigoJugadores(String JugadorActual) {
        PonerNombreJugador.setText("Cartas de " + JugadorActual);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        PonerNombreJugador = new javax.swing.JLabel();
        tomarCarta = new javax.swing.JButton();
        Baraja = new javax.swing.JButton();
        BotonCartaTop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aventura en el Reino de las Sombras");

        jPanel2.setPreferredSize(new java.awt.Dimension(1300, 700));

        jButton2.setPreferredSize(new java.awt.Dimension(150, 100));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        PonerNombreJugador.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        PonerNombreJugador.setText("...");

        tomarCarta.setText("Tomar Carta");
        tomarCarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomarCartaActionPerformed(evt);
            }
        });

        Baraja.setPreferredSize(new java.awt.Dimension(106, 156));
        Baraja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarajaActionPerformed(evt);
            }
        });

        BotonCartaTop.setIcon(new javax.swing.ImageIcon("C:\\Users\\Joseph F\\Desktop\\IMAGES\\Back\\BACK_SIDE.png")); // NOI18N
        BotonCartaTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCartaTopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PonerNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonCartaTop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Baraja, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(227, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tomarCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Baraja, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonCartaTop, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(tomarCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(PonerNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1359, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tomarCartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomarCartaActionPerformed
        JLabel mensaje = new JLabel(juego.obtenerJugadorActual() + " a tomado una carta.");
        mensaje.setFont(new Font("Arial", Font.BOLD, 48));
        JOptionPane.showMessageDialog(null, mensaje);
        try {
            juego.realizarRobo(juego.obtenerJugadorActual());
        } catch (JugadorTurnoInvalidoException ex) {
            Logger.getLogger(GameStage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BarajaUno.BarajaVaciaException ex) {
            Logger.getLogger(GameStage.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.PonerCodigoJugadores(juego.obtenerJugadorActual());
        this.ponerIconoBotones();
    }//GEN-LAST:event_tomarCartaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (IdCartas.get(0) != null) {
            int index = 0;
            String IdCarta = IdCartas.get(0);
            ventana = new PopUp(IdCarta, juego, index, BotonesCarta, this, BotonCartaTop);
            ventana.setBounds(750, 40, 700, 800);
            ventana.setResizable(false);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (IdCartas.get(1) != null) {
            int index = 1;
            String IdCarta = IdCartas.get(1);
            ventana = new PopUp(IdCarta, juego, index, BotonesCarta, this, BotonCartaTop);
            ventana.setBounds(750, 40, 700, 800);
            ventana.setResizable(false);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (IdCartas.get(2) != null) {
            int index = 2;
            String IdCarta = IdCartas.get(2);
            ventana = new PopUp(IdCarta, juego, index, BotonesCarta, this, BotonCartaTop);
            ventana.setBounds(750, 40, 700, 800);
            ventana.setResizable(false);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (IdCartas.get(3) != null) {
            int index = 3;
            String IdCarta = IdCartas.get(3);
            ventana = new PopUp(IdCarta, juego, index, BotonesCarta, this, BotonCartaTop);
            ventana.setBounds(750, 40, 700, 800);
            ventana.setResizable(false);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (IdCartas.get(4) != null) {
            int index = 4;
            String IdCarta = IdCartas.get(4);
            ventana = new PopUp(IdCarta, juego, index, BotonesCarta, this, BotonCartaTop);
            ventana.setBounds(750, 40, 700, 800);
            ventana.setResizable(false);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (IdCartas.get(4) != null) {
            int index = 4;
            String IdCarta = IdCartas.get(4);
            ventana = new PopUp(IdCarta, juego, index, BotonesCarta, this, BotonCartaTop);
            ventana.setBounds(750, 40, 700, 800);
            ventana.setResizable(false);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (IdCartas.get(5) != null) {
            int index = 5;
            String IdCarta = IdCartas.get(5);
            ventana = new PopUp(IdCarta, juego, index, BotonesCarta, this, BotonCartaTop);
            ventana.setBounds(750, 40, 700, 800);
            ventana.setResizable(false);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (IdCartas.get(6) != null) {
            int index = 6;
            String IdCarta = IdCartas.get(6);
            ventana = new PopUp(IdCarta, juego, index, BotonesCarta, this, BotonCartaTop);
            ventana.setBounds(750, 40, 700, 800);
            ventana.setResizable(false);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (IdCartas.get(7) != null) {
            int index = 7;
            String IdCarta = IdCartas.get(7);
            ventana = new PopUp(IdCarta, juego, index, BotonesCarta, this, BotonCartaTop);
            ventana.setBounds(750, 40, 700, 800);
            ventana.setResizable(false);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if (IdCartas.get(8) != null) {
            int index = 8;
            String IdCarta = IdCartas.get(8);
            ventana = new PopUp(IdCarta, juego, index, BotonesCarta, this, BotonCartaTop);
            ventana.setBounds(750, 40, 700, 800);
            ventana.setResizable(false);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void BarajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarajaActionPerformed
        //BotonCartaTop();
    }//GEN-LAST:event_BarajaActionPerformed

    private void BotonCartaTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCartaTopActionPerformed
        JOptionPane.showMessageDialog(this, "Esta no es la baraja!");
    }//GEN-LAST:event_BotonCartaTopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameStage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameStage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameStage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameStage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameStage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Baraja;
    private javax.swing.JButton BotonCartaTop;
    private javax.swing.JLabel PonerNombreJugador;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton tomarCarta;
    // End of variables declaration//GEN-END:variables

}
